#!/bin/sh

export AUTOM4TE="autom4te"
export AUTOCONF="autoconf"

case X${1}X in
XcleanX)
    rm -fr ar-lib
    rm -fr autom4te.cache
    rm -fr m4/lt~obsolete.m4 m4/ltsugar.m4 m4/libtool.m4
    rm -fr m4/ltoptions.m4 m4/ltversion.m4
    for fname in aclocal.m4 compile configure config.guess config.log \
                 config.status config.sub depcomp install-sh ltmain.sh \
                 libtool missing mkinstalldirs Makefile; do
        rm -f $fname
    done
    find . -name Makefile.in -delete
    find . -name Makefile -delete
    find . -name '.deps' -prune -exec rm -fr {} \;
    ;;

XinitX)
    set -x
    mkdir -p m4
    aclocal -I m4 -I .
    libtoolize --automake --copy --force
    autoconf --force
    autoheader
    automake --add-missing --copy --foreign -Woverride
    chmod +x configure
    ./configure
    ;;

XX)
    $0 init
    ;;
esac
